package szysz3.planty.domain.model

data class Plant(
    val id: Int,
    val latinName: String,
    val family: String? = null,
    val commonName: String? = null,
    val habit: String? = null,
    val deciduousEvergreen: String? = null,
    val height: Float? = null,
    val width: Float? = null,
    val ukHardiness: Int? = null,
    val medicinal: String? = null,
    val range: String? = null,
    val habitat: String? = null,
    val soil: String? = null,
    val shade: String? = null,
    val moisture: String? = null,
    val wellDrained: Boolean? = null,
    val nitrogenFixer: Boolean? = null,
    val ph: String? = null,
    val acid: Boolean? = null,
    val alkaline: Boolean? = null,
    val saline: Boolean? = null,
    val wind: Boolean? = null,
    val growthRate: String? = null,
    val pollution: Boolean? = null,
    val poorSoil: Boolean? = null,
    val drought: Boolean? = null,
    val wildlife: String? = null,
    val pollinators: String? = null,
    val selfFertile: Boolean? = null,
    val knownHazards: String? = null,
    val synonyms: String? = null,
    val cultivationDetails: String? = null,
    val edibleUses: String? = null,
    val usesNotes: String? = null,
    val propagation: String? = null,
    val heavyClay: Boolean? = null,
    val edibilityRating: Int? = null,
    val frostTender: Boolean? = null,
    val scented: Boolean? = null,
    val medicinalRating: Int? = null,
)