package szysz3.planty.domain.util

import szysz3.planty.domain.model.Plant

object TestPlantFactory {

    fun createPlant(
        id: Int = 101,
        latinName: String = "Ficus lyrata",
        family: String? = "Moraceae",
        commonName: String? = "Fiddle Leaf Fig",
        habit: String? = "Evergreen tree",
        deciduousEvergreen: String? = "Evergreen",
        height: Float? = 3.0f,
        width: Float? = 2.0f,
        ukHardiness: Int? = 8,
        medicinal: String? = "None",
        range: String? = "Native to Western Africa",
        habitat: String? = "Rainforests",
        soil: String? = "Well-drained",
        shade: String? = "Partial shade",
        moisture: String? = "Moderate",
        wellDrained: Boolean? = true,
        nitrogenFixer: Boolean? = false,
        ph: String? = "6.0-7.5",
        acid: Boolean? = false,
        alkaline: Boolean? = true,
        saline: Boolean? = false,
        wind: Boolean? = false,
        growthRate: String? = "Fast",
        pollution: Boolean? = false,
        poorSoil: Boolean? = false,
        drought: Boolean? = false,
        wildlife: String? = "Birds",
        pollinators: String? = "Bees",
        selfFertile: Boolean? = true,
        knownHazards: String? = "None",
        synonyms: String? = "Ficus lyrata var. vera",
        cultivationDetails: String? = "Requires bright, indirect light",
        edibleUses: String? = "None",
        usesNotes: String? = "Popular houseplant",
        propagation: String? = "Stem cuttings",
        heavyClay: Boolean? = false,
        edibilityRating: Int? = null,
        frostTender: Boolean? = true,
        scented: Boolean? = false,
        medicinalRating: Int? = null,
        imageUrls: List<String>? = listOf("http://example.com/image1.jpg")
    ): Plant {
        return Plant(
            id = id,
            latinName = latinName,
            family = family,
            commonName = commonName,
            habit = habit,
            deciduousEvergreen = deciduousEvergreen,
            height = height,
            width = width,
            ukHardiness = ukHardiness,
            medicinal = medicinal,
            range = range,
            habitat = habitat,
            soil = soil,
            shade = shade,
            moisture = moisture,
            wellDrained = wellDrained,
            nitrogenFixer = nitrogenFixer,
            ph = ph,
            acid = acid,
            alkaline = alkaline,
            saline = saline,
            wind = wind,
            growthRate = growthRate,
            pollution = pollution,
            poorSoil = poorSoil,
            drought = drought,
            wildlife = wildlife,
            pollinators = pollinators,
            selfFertile = selfFertile,
            knownHazards = knownHazards,
            synonyms = synonyms,
            cultivationDetails = cultivationDetails,
            edibleUses = edibleUses,
            usesNotes = usesNotes,
            propagation = propagation,
            heavyClay = heavyClay,
            edibilityRating = edibilityRating,
            frostTender = frostTender,
            scented = scented,
            medicinalRating = medicinalRating,
            imageUrls = imageUrls
        )
    }
}
